server:
    port: "8080"
    mode: "debug"
mysql:
    host: "localhost"
    port: "3306"
    account: "root"
    password: "root"
    dbname: "flash_sale"
redis:
    host: "localhost"
    port: "6379"
    password: "123456"
    dbname: 0
rabbitmq:
    host: "localhost"
    port: "5672"
    account: "hycer"
    password: "123456"
